version: "3.2"
services:
   elasticsearch:
     build: elastic 
     ports:
       - "9200:9200"
   kibana:
     build: kibana 
     ports:
       - "5601:5601"
     links:
       - "elasticsearch"
   filebeat:
     build: filebeat
     links:
       - "elasticsearch"
